import mongoose from 'mongoose';
import IWallpaper from '../interfaces/wallpaper';
import users from './user';
import { workMusic as musicId, user as userId } from './ids';
import faker from 'faker';

const musics = [
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[0],
    creator: userId[2],
    musicUrl: '1.mp3',
    imageUrl: '1.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[1],
    creator: userId[2],
    musicUrl: '2.mp3',
    imageUrl: '2.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[2],
    creator: userId[2],
    musicUrl: '3.mp3',
    imageUrl: '3.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[3],
    creator: userId[2],
    musicUrl: '4.mp3',
    imageUrl: '4.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[4],
    creator: userId[2],
    musicUrl: '5.mp3',
    imageUrl: '5.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[5],
    creator: userId[2],
    musicUrl: '6.mp3',
    imageUrl: '6.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[6],
    creator: userId[2],
    musicUrl: '7.mp3',
    imageUrl: '7.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[7],
    creator: userId[2],
    musicUrl: '8.mp3',
    imageUrl: '8.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[8],
    creator: userId[2],
    musicUrl: '9.mp3',
    imageUrl: '9.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[9],
    creator: userId[2],
    musicUrl: '10.mp3',
    imageUrl: '10.jpg',
    title: faker.name.title(),
  },





  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[10],
    creator: userId[2],
    musicUrl: '11.mp3',
    imageUrl: '11.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[11],
    creator: userId[2],
    musicUrl: '12.mp3',
    imageUrl: '12.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[12],
    creator: userId[2],
    musicUrl: '13.mp3',
    imageUrl: '13.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[13],
    creator: userId[2],
    musicUrl: '14.mp3',
    imageUrl: '14.jpg',
    title: faker.name.title(),
  },
  {
    public: true,
    genres: ['기타음악'],
    moods: ['고독'],
    instruments: ['대금'],
    ref: [],
    owner: musicId[14],
    creator: userId[2],
    musicUrl: '15.mp3',
    imageUrl: '15.jpg',
    title: faker.name.title(),
  },
];


export default musics;
