import mongoose from 'mongoose';
import faker from 'faker';
import users from './user';
import { IWorkImage, IWorkImageContent } from '../interfaces/workImage';

import { workMusic as musicId, user as userId } from './ids';
import musics from './music';

const workMusics = [
  {
    _id: musicId[0],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[0].musicUrl,
            imageUrl: musics[0].imageUrl,
            title: musics[0].title,
            genres: musics[0].genres,
            moods: musics[0].moods,
            instruments: musics[0].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[1],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[1].musicUrl,
            imageUrl: musics[1].imageUrl,
            title: musics[1].title,
            genres: musics[1].genres,
            moods: musics[1].moods,
            instruments: musics[1].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[2],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[2].musicUrl,
            imageUrl: musics[2].imageUrl,
            title: musics[2].title,
            genres: musics[2].genres,
            moods: musics[2].moods,
            instruments: musics[2].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[3],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[3].musicUrl,
            imageUrl: musics[3].imageUrl,
            title: musics[3].title,
            genres: musics[3].genres,
            moods: musics[3].moods,
            instruments: musics[3].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[4],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[4].musicUrl,
            imageUrl: musics[4].imageUrl,
            title: musics[4].title,
            genres: musics[4].genres,
            moods: musics[4].moods,
            instruments: musics[4].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[5],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[5].musicUrl,
            imageUrl: musics[5].imageUrl,
            title: musics[5].title,
            genres: musics[5].genres,
            moods: musics[5].moods,
            instruments: musics[5].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[6],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[6].musicUrl,
            imageUrl: musics[6].imageUrl,
            title: musics[6].title,
            genres: musics[6].genres,
            moods: musics[6].moods,
            instruments: musics[6].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[7],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[7].musicUrl,
            imageUrl: musics[7].imageUrl,
            title: musics[7].title,
            genres: musics[7].genres,
            moods: musics[7].moods,
            instruments: musics[7].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[8],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[8].musicUrl,
            imageUrl: musics[8].imageUrl,
            title: musics[8].title,
            genres: musics[8].genres,
            moods: musics[8].moods,
            instruments: musics[8].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[9],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[9].musicUrl,
            imageUrl: musics[9].imageUrl,
            title: musics[9].title,
            genres: musics[9].genres,
            moods: musics[9].moods,
            instruments: musics[9].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[10],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[10].musicUrl,
            imageUrl: musics[10].imageUrl,
            title: musics[10].title,
            genres: musics[10].genres,
            moods: musics[10].moods,
            instruments: musics[10].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[11],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[11].musicUrl,
            imageUrl: musics[11].imageUrl,
            title: musics[11].title,
            genres: musics[11].genres,
            moods: musics[11].moods,
            instruments: musics[11].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[12],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[12].musicUrl,
            imageUrl: musics[12].imageUrl,
            title: musics[12].title,
            genres: musics[12].genres,
            moods: musics[12].moods,
            instruments: musics[12].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[13],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[13].musicUrl,
            imageUrl: musics[13].imageUrl,
            title: musics[13].title,
            genres: musics[13].genres,
            moods: musics[13].moods,
            instruments: musics[13].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
  {
    _id: musicId[14],
    owner: userId[2],
    title: faker.name.title(),
    content: [
      {
        type: 'musics',
        content: {
            musicUrl: musics[14].musicUrl,
            imageUrl: musics[14].imageUrl,
            title: musics[14].title,
            genres: musics[14].genres,
            moods: musics[14].moods,
            instruments: musics[14].instruments,
        },
      },
      {
        type: 'description',
        content: faker.lorem.sentence(),
      },
    ],
    comments: [],
    commentsAllow: true,
    ccl: 'all rights reserved',
    field: '음악',
    public: true,
    tags: ['t', 'a', 'g', 's'],
    views: faker.random.number(234),
  },
];

export default workMusics;
